# ------------------------------------------
# Minimal Mistakes Basic Configuration
# ------------------------------------------

# Use the remote theme or your local fork
# remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "dark"  # try "dark", "air", "contrast", etc.

title: "Angelo's Blog"
name: "Angelo Rosu"
description: "Exploring AI, Quant Finance, and Research."
locale: "en-US"

# Important: your GitHub Pages URL
url: "https://angelorosu.github.io"
baseurl: ""

# Make sure this matches your GitHub repo "username/repo"
repository: "angelorosu/angelorosu.github.io"

# Remove the big author card site-wide (we can enable per post if we want)
author_profile: false

# ------------------------------------------
# NAVIGATION (Optional)
# ------------------------------------------
# If you want a top nav bar, define it here or in _data/navigation.yml
navigation:
  - title: "Home"
    url: "/"
  # - title: "About"
  #   url: "/about/"
  # - title: "Blog"
  #   url: "/blog/"
  # Add or remove as needed

# ------------------------------------------
# PLUGINS
# ------------------------------------------
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# ------------------------------------------
# LAYOUT + STYLE
# ------------------------------------------
font:
  heading: "Poppins"
  body: "Lora"

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5  # show 5 posts on homepage
paginate_path: "/page:num/"

# ------------------------------------------
# DEFAULTS (Layout for new posts)
# ------------------------------------------
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
