# Angelo's Blog Configuration File for Minimal Mistakes Theme

# Theme Settings
minimal_mistakes_skin: "default"  # Options: "default", "air", "aqua", "contrast", etc.

# Site Settings
locale: "en-US"
rtl: false
title: "Angelo's Blog"
title_separator: "-"
subtitle: ""
name: "Angelo Rosu"
description: "Exploring AI, Quant Finance, and Research."
url: "https://angelorosu.github.io"  # Your full site URL
baseurl: ""                         # Leave empty since the site is at the root
repository: "angelorosu/angelorosu.github.io"
teaser: ""
logo: ""
masthead_title: ""
breadcrumbs: false
words_per_minute: 200
enable_copy_code_button: false
copyright: "Angelo's Blog"
copyright_url: "https://angelorosu.github.io"

# Comments (disabled by default)
comments:
  provider: false
  disqus:
    shortname: ""
  discourse:
    server: ""
  facebook:
    appid: ""
    num_posts: 5
    colorscheme: "light"
  utterances:
    theme: "github-light"
    issue_term: "pathname"
  giscus:
    repo_id: ""
    category_name: ""
    category_id: ""
    discussion_term: "pathname"
    reactions_enabled: '1'
    theme: "light"
    strict: 0
    input_position: "top"
    emit_metadata: 0
    lang: "en"
    lazy: false
  staticman:
    branch: "master"
    endpoint: ""

reCaptcha:
  siteKey: ""
  secret: ""

atom_feed:
  path: ""  # Defaults to feed.xml if left blank
  hide: false

search: false
search_full_content: false
search_provider: "lunr"
lunr:
  search_within_pages: false
algolia:
  application_id: ""
  index_name: ""
  search_only_api_key: ""
  powered_by: true
google:
  search_engine_id: ""
  instant_search: false

google_site_verification: ""
bing_site_verification: ""
naver_site_verification: ""
yandex_site_verification: ""
baidu_site_verification: ""

# Social Sharing and Profiles
twitter:
  username: ""
facebook:
  username: ""
  app_id: ""
  publisher: ""
og_image: ""
social:
  type: ""
  name: ""
  links: []  # Add social links as needed

# Analytics
analytics:
  provider: false
  google:
    tracking_id: ""
    anonymize_ip: false

# Site Author
author:
  name: "Angelo Rosu"
  avatar: ""  # e.g., "/assets/images/bio-photo.jpg"
  bio: "I am an amazing person exploring AI, Quant Finance, and Research."
  location: ""
  email: ""
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
    - label: "Website"
      icon: "fas fa-fw fa-link"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown Conversion and Processing
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS Settings
sass:
  sass_dir: _sass
  style: compressed

# Permalinks
permalink: /:categories/:title/
timezone: ""

# Pagination (jekyll-paginate)
paginate: 5
paginate_path: /page:num/

# Pagination (jekyll-paginate-v2)
pagination:
  debug: false
  collection: "posts"
  per_page: 10
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after: 2

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
